config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #All of our Resources
  resources :customers
  resources :employees
  resources :additions
  resources :foods
  resources :temp_orders
  resources :orders
  resources :food_tags

  #The Home Page of the website
  root 'pages#home'
  #addition !!
  #This will be our testing file for things you would like to testout using the website: (Please Comment this route out when development is over)
  get 'test', to: 'menu#testing', as: 'test'

  #Employee Routes 
  get 'n1e2w3E4m5p6l7o8y9e0R1e2g3i4s5t6e7r8', to: 'employees#admin', as: 'employees_login' #Adding New Employees
  get '1a2d3m4i5n6H7u8b', to: 'employees#home', as: 'employees_home' #Administration Hub :: if the Authorization Key inst correct will redirect you to login or to Non Admin Orders View
  get '1c2u3s4t5o6m7e8r9O0r1d2e3r4s', to: 'employees#orders', as: 'customer_orders' #Customer's Order View :: Shows all non started orders
  get '1E2m3p4l5o6y7e8L9o0g1i2n', to: 'employees#login', as: 'employees_admin_login' #Employee Login
  get 'o1l2d3O4r5d6e7r8s9', to: 'employees#oldOrders', as: 'employees_old_orders' #Employee Login

  #Routes for customers to order Items
  get 'confirmation', to: 'menu#confirmation', as: 'order_confirmation'
  get 'orderingMenu', to: 'menu#orderingMenu', as: 'ordering_menu'
  get 'order', to: 'menu#order', as: 'menu_order'
  get 'login', to: 'menu#login'
  get 'icecreamMenu', to: 'menu#iceCreamMenu', as: 'ice_memu'

  #Setting what menu will be shown for the ordering menu 
  get '/set_isBreakfast_true', to: 'menu#set_isBreakfast_true'
  get '/set_isBreakfast_false', to: 'menu#set_isBreakfast_false'

  #Methods in the Employees Controller
  post 'storing_additions', to: 'employees#addition'
  post 'deletingAdditions', to: 'employees#deletingAdditions'
  post 'deletingFoods', to: 'employees#deletingFoods'
  post 'addingNewFood', to: 'employees#addingFood'
  post 'completingOrder', to: 'employees#completingOrder'
  post 'changingTag', to: 'employees#changingTag'
  post 'deletingTags', to: 'employees#deletingTags'
  post 'updatingFoodAdditions', to: 'employees#updatingFoodAdditions'
  post 'checkCredentials', to: 'employees#checkCredentials'
  post 'adminKey', to: 'employees#adminKey'

  #Theses Methods are for forums inside of the menu controller
  post 'deleteTempOrderItem', to: 'menu#deleteTempOrderItem'
  post 'updatingCustomersOrder', to: 'menu#updatingCustomersOrder'

  Rails.application.routes.draw do
    get 'menu/show/:id', to: 'menu#show', as: 'menu_show' # Define a route for showing food details
  end

  Rails.application.routes.draw do
    get 'employees/show/:id', to: 'employees#show', as: 'employees_show' # Define a route for showing food details
  end

end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    def home
        @additions = Addition.all
        @foods = Food.all
        @orders = Order.all
        @foodTags = FoodTag.all

        if session[:authorization_key] == "54321"
        elsif session[:employee].blank? || session[:employee].nil?
            redirect_to employees_admin_login_url
        else
            redirect_to customer_orders_url
        end
    end

    def show
        @food = Food.find(params[:id])
        @additions = Addition.all
    end

    def oldOrders
        @oldOrders = Order.where(completed_order: 3)
    end
    
    def checkCredentials
        username = params[:username]
        password = params[:password]
        employee = Employee.find_by(username: username, password: password)
        if !employee.nil?
            session[:employee] = employee
            session[:authorization_key] = employee.authorization_key
            redirect_to customer_orders_url
        else
            redirect_to employees_admin_login_url
        end
    end

    def adminKey
        session[:authorization_key] = params[:authorizationKey]
        if session[:authorization_key] == "54321"
            redirect_to employees_home_url
        else
            redirect_to customer_orders_path
        end
    end
      

    def updatingFoodAdditions
        @food = Food.find(params[:id])
        @food.food_additions = params[:foodAdditions]
        if @food.save
            redirect_to employees_home_url
        else
            render root_url
        end
    end

    def addition #This is how we are storing each addition into an array before we add it to the food item
        session[:addition] ||= []
        session[:addition] << params[:your_variable]
        redirect_to employees_home_url
    end

    def addingFood #Adding a food to the Food DB table: This will reset the session array 
        @food = Food.new
        @food.food_additions = (session[:addition] || []).map { |json_str| JSON.parse(json_str) } || []
        @food.food_modifiables = ""
        @food.food_name = params[:food_name]
        @food.inital_cost = params[:inital_cost]
        @food.isBreakfast = params[:isBreakfast]
        @food.description = params[:description] || ""
        @food.tag = params[:tag]
    
        session[:addition] = []
    
        if @food.save
            redirect_to employees_home_url
        else
            render root_url
        end
    end

    def admin
        session[:isCompleted] ||= true
        @employee = Employee.new
    end

    def orders
        @orders = Order.all
        if session[:employee].blank? || session[:employee].nil?
            redirect_to employees_admin_login_url
        end
    end

    def changingTag
        @food = Food.find(params[:id])
        @food.tag = params[:newTag]
        if @food.save
            redirect_to employees_home_url
        else
            render 'home'
        end
    end

    def deletingTags
        @tag = FoodTag.find(params[:id])
        @foods = Food.where(tag: @tag.food_Tag_Name)
        @foods.each do |food|
          food.update(tag: nil)
        end
        if @tag.destroy
          redirect_to employees_home_url
        else
          render 'home'
        end
    end

    def deletingAdditions
        @addition = Addition.find(params[:id])
        if @addition.destroy
            redirect_to employees_home_url
        else
            render 'home'
        end
    end

    def deletingFoods
        @food = Food.find(params[:id])
        if @food.destroy
          redirect_to employees_home_url
        else
          render 'home'
        end
    end

    def completingOrder
        @order = Order.find(params[:id])
      
        # Use a 3-way toggle for completed_order
        @order.completed_order = case @order.completed_order
        when 0 then 1
        when 1 then 2
        when 2 then 3
        else 1
        end
      
        if @order.save
          redirect_to orders_path, notice: "Order updated successfully."
        else
          render :edit
        end
    end
    
    def create
        @employee = Employee.new(employee_params)
        if @employee.save
          redirect_to  employees_home_url
        else
          render 'home'
        end
    end
      
    private
    def employee_params
        params.require(:employee).permit(:username, :password, :phone_number, :authorization_key)
    end   

    private
    def order_params
        params.require(:order).permit(:completed_order)
    end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employee/login.html.erb
<% @include_prose_class = true %>



<%= form_for Addition.new, url: additions_path do |f| %>
  <div class="mt-4">
    <%= f.label :addition_name, "Addition Name", class: "block font-bold" %>
    <%= f.text_field :addition_name, placeholder: "Enter the addition name", class: "border p-2 w-full" %>
  </div>
  <div class="mt-4">
    <%= f.label :cost, "Cost", class: "block font-bold" %>
    <%= f.number_field :cost, step: 0.01, placeholder: "Enter the cost", class: "border p-2 w-full" %>
  </div>
  <div class="mt-4">
    <%= f.submit "Add Addition", class: "bg-blue-500 text-white p-2 rounded" %>
  </div>
<% end %>

<table class="mt-8">
  <tr>
    <th class="px-4 py-2">Food Addition</th>
    <th class="px-4 py-2">Cost</th>
    <th class="px-4 py-2">Action</th>
  </tr>
  <% if @additions.any? %>
    <% @additions.each do |addition| %>
      <tr>
        <td class="px-4 py-2"><%= addition.addition_name %></td>
        <td class="px-4 py-2"><%= addition.cost %></td>
        <td class="px-4 py-2">
          <%= form_tag storing_additions_path, method: :post do %>
            <%= hidden_field_tag :your_variable, addition.to_json %>
            <%= submit_tag "Store Variable", class: "bg-blue-500 text-white p-2 rounded" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td class="px-4 py-2" colspan="3">No additions available.</td>
    </tr>
  <% end %>
</table>

<% if !session[:addition].blank? %>
  <% session[:addition].each do |x| %>
    <% object = JSON.parse(x) %>
    <%= object.inspect %>
    <h4 class="mt-4">ITS WORKING: <%= object["id"] %></h4>
  <% end %>
<% end %>

<%= form_with(model: @food, url: addingNewFood_path, method: :post) do |form| %>
  <%= form.text_field :food_name, class: "border p-2 w-full" %>
  <%= form.hidden_field :food_additions, value: session[:addition] %>
  <%= form.hidden_field :food_modifiables, value: "" %>
  <%= form.number_field :inital_cost, step: 0.01, class: "border p-2 w-full" %>
  <div class="mt-4">
    <%= form.label :autolyse, "Breakfast", class: "block font-bold" %>
    <%= form.radio_button :isBreakfast, true, class: "mr-2" %>
    <%= form.label :autolyse, "Lunch/Dinner", class: "block font-bold" %>
    <%= form.radio_button :isBreakfast, false, class: "mr-2" %>
  </div>
  <%= form.submit "Add Food", class: "bg-blue-500 text-white p-2 rounded mt-4" %>
<% end %>

<table class="mt-8">
  <tr>
    <th class="px-4 py-2">Food Name</th>
    <th class="px-4 py-2">Food Mods</th>
    <th class="px-4 py-2">Total Cost</th>
    <th class="px-4 py-2">Breakfast Or Lunch/Dinner</th>
  </tr>
  <% if !@foods.blank? %>
    <% @foods.each do |fooditem| %>
      <tr>
        <td class="px-4 py-2"><%= fooditem.food_name %></td>
        <% data = eval(fooditem.food_additions) rescue [] %>
        <% additions = data.is_a?(Array) ? data : [data] %>
        <td class="px-4 py-2">
          <% additions.each do |addition| %>
            <h4>ID: <%= addition['id'] %>, Name: <%= addition['addition_name'] %>, Cost: <%= addition['cost'] %></h4>
          <% end %>
        </td>
        <td class="px-4 py-2"><%= fooditem.inital_cost %></td>
        <td class="px-4 py-2">
          <% if fooditem.isBreakfast == true %>
            Breakfast
          <% else %>
            Lunch
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

<h1 class="mt-8">Order Database</h1>
<table class="mt-4">
  <tr>
    <th class="px-4 py-2">Customer Id</th>
    <th class="px-4 py-2">Order Id</th>
    <th class="px-4 py-2">Food Ids</th>
    <th class="px-4 py-2">Food Mods</th>
    <th class="px-4 py-2">Total Cost</th>
  </tr>
  <% if !@orders.blank? %>
    <% @orders.each do |order| %>
      <tr>
        <td class="px-4 py-2"><%= order.customer_id %></td>
        <td class="px-4 py-2"><%= order.order_id %></td>
        <td class="px-4 py-2"><%= order.list_food_id %></td>
        <td class="px-4 py-2"><%= order.list_food_notes %></td>
        <td class="px-4 py-2"><%= order.total_cost %></td>
        <td class="px-4 py-2"><%= order.completed_order %></td>
      </tr>
    <% end %>
  <% end %>
</table>