config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #All of our Resources
  resources :customers
  resources :employees
  resources :additions
  resources :foods
  resources :temp_orders
  resources :orders
  resources :food_tags

  #The Home Page of the website
  root 'pages#home'
  #addition !!
  #This will be our testing file for things you would like to testout using the website: (Please Comment this route out when development is over)
  get 'test', to: 'menu#testing', as: 'test'

  #Employee Routes 
  get 'n1e2w3E4m5p6l7o8y9e0R1e2g3i4s5t6e7r8', to: 'employees#admin', as: 'employees_login' #Adding New Employees
  get '1a2d3m4i5n6H7u8b', to: 'employees#home', as: 'employees_home' #Administration Hub :: if the Authorization Key inst correct will redirect you to login or to Non Admin Orders View
  get '1c2u3s4t5o6m7e8r9O0r1d2e3r4s', to: 'employees#orders', as: 'customer_orders' #Customer's Order View :: Shows all non started orders
  get '1E2m3p4l5o6y7e8L9o0g1i2n', to: 'employees#login', as: 'employees_admin_login' #Employee Login
  get 'o1l2d3O4r5d6e7r8s9', to: 'employees#oldOrders', as: 'employees_old_orders' #Employee Login

  #Routes for customers to order Items
  get 'confirmation', to: 'menu#confirmation', as: 'order_confirmation'
  get 'orderingMenu', to: 'menu#orderingMenu', as: 'ordering_menu'
  get 'order', to: 'menu#order', as: 'menu_order'
  get 'login', to: 'menu#login'
  get 'icecreamMenu', to: 'menu#iceCreamMenu', as: 'ice_memu'

  #Setting what menu will be shown for the ordering menu 
  get '/set_isBreakfast_true', to: 'menu#set_isBreakfast_true'
  get '/set_isBreakfast_false', to: 'menu#set_isBreakfast_false'

  #Methods in the Employees Controller
  post 'storing_additions', to: 'employees#addition'
  post 'deletingAdditions', to: 'employees#deletingAdditions'
  post 'deletingFoods', to: 'employees#deletingFoods'
  post 'addingNewFood', to: 'employees#addingFood'
  post 'completingOrder', to: 'employees#completingOrder'
  post 'changingTag', to: 'employees#changingTag'
  post 'deletingTags', to: 'employees#deletingTags'
  post 'updatingFoodAdditions', to: 'employees#updatingFoodAdditions'
  post 'checkCredentials', to: 'employees#checkCredentials'
  post 'adminKey', to: 'employees#adminKey'

  #Theses Methods are for forums inside of the menu controller
  post 'deleteTempOrderItem', to: 'menu#deleteTempOrderItem'
  post 'updatingCustomersOrder', to: 'menu#updatingCustomersOrder'

  Rails.application.routes.draw do
    get 'menu/show/:id', to: 'menu#show', as: 'menu_show' # Define a route for showing food details
  end

  Rails.application.routes.draw do
    get 'employees/show/:id', to: 'employees#show', as: 'employees_show' # Define a route for showing food details
  end

end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    def home
        @additions = Addition.all
        @foods = Food.all
        @orders = Order.all
        @foodTags = FoodTag.all

        if session[:authorization_key] == "54321"
        elsif session[:employee].blank? || session[:employee].nil?
            redirect_to employees_admin_login_url
        else
            redirect_to customer_orders_url
        end
    end

    def show
        @food = Food.find(params[:id])
        @additions = Addition.all
    end

    def oldOrders
        @oldOrders = Order.where(completed_order: 3)
    end
    
    def checkCredentials
        username = params[:username]
        password = params[:password]
        employee = Employee.find_by(username: username, password: password)
        if !employee.nil?
            session[:employee] = employee
            session[:authorization_key] = employee.authorization_key
            redirect_to customer_orders_url
        else
            redirect_to employees_admin_login_url
        end
    end

    def adminKey
        session[:authorization_key] = params[:authorizationKey]
        if session[:authorization_key] == "54321"
            redirect_to employees_home_url
        else
            redirect_to customer_orders_path
        end
    end
      

    def updatingFoodAdditions
        @food = Food.find(params[:id])
        @food.food_additions = params[:foodAdditions]
        if @food.save
            redirect_to employees_home_url
        else
            render root_url
        end
    end

    def addition #This is how we are storing each addition into an array before we add it to the food item
        session[:addition] ||= []
        session[:addition] << params[:your_variable]
        redirect_to employees_home_url
    end

    def addingFood #Adding a food to the Food DB table: This will reset the session array 
        @food = Food.new
        @food.food_additions = (session[:addition] || []).map { |json_str| JSON.parse(json_str) } || []
        @food.food_modifiables = ""
        @food.food_name = params[:food_name]
        @food.inital_cost = params[:inital_cost]
        @food.isBreakfast = params[:isBreakfast]
        @food.description = params[:description] || ""
        @food.tag = params[:tag]
    
        session[:addition] = []
    
        if @food.save
            redirect_to employees_home_url
        else
            render root_url
        end
    end

    def admin
        session[:isCompleted] ||= true
        @employee = Employee.new
    end

    def orders
        @orders = Order.all
        if session[:employee].blank? || session[:employee].nil?
            redirect_to employees_admin_login_url
        end
    end

    def changingTag
        @food = Food.find(params[:id])
        @food.tag = params[:newTag]
        if @food.save
            redirect_to employees_home_url
        else
            render 'home'
        end
    end

    def deletingTags
        @tag = FoodTag.find(params[:id])
        @foods = Food.where(tag: @tag.food_Tag_Name)
        @foods.each do |food|
          food.update(tag: nil)
        end
        if @tag.destroy
          redirect_to employees_home_url
        else
          render 'home'
        end
    end

    def deletingAdditions
        @addition = Addition.find(params[:id])
        if @addition.destroy
            redirect_to employees_home_url
        else
            render 'home'
        end
    end

    def deletingFoods
        @food = Food.find(params[:id])
        if @food.destroy
          redirect_to employees_home_url
        else
          render 'home'
        end
    end

    def completingOrder
        @order = Order.find(params[:id])
      
        # Use a 3-way toggle for completed_order
        @order.completed_order = case @order.completed_order
        when 0 then 1
        when 1 then 2
        when 2 then 3
        else 1
        end
      
        if @order.save
          redirect_to orders_path, notice: "Order updated successfully."
        else
          render :edit
        end
    end
    
    def create
        @employee = Employee.new(employee_params)
        if @employee.save
          redirect_to  employees_home_url
        else
          render 'home'
        end
    end
      
    private
    def employee_params
        params.require(:employee).permit(:username, :password, :phone_number, :authorization_key)
    end   

    private
    def order_params
        params.require(:order).permit(:completed_order)
    end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/admin.html.erb
<% @include_prose_class = true %>


<style>
/* app/assets/stylesheets/custom.css.scss */

.custom-bg-color {
  background-color: #0CC0DF;
  transition: background-color 0.3s ease; /* Add a smooth transition effect */
}
 
.custom-bg-color:hover {
  background-color: #687EFF; /* Change to the hover color you want */
}

</style> 

<div style="padding-top:30px !important; padding-bottom:30px !important">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <div class="absolute inset-0 bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl"></div>
    <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">

      <div class="max-w-md mx-auto">
        <div>
          <h1 class="text-2xl font-semibold">Before you make a new employee, we need some information...</h1>
        </div>
        <div class="divide-y divide-gray-200">
          <%= form_for @employee, html: { class: 'py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7' } do |f| %>
            <div class="relative">
              <%= f.label :username, class: 'block text-gray-600 text-sm font-bold mb-2' %>
              <%= f.text_field :username, name: "employee[username]", class: 'w-full p-2 rounded border focus:outline-none focus:ring focus:border-blue-300' %>
            </div>  

            <div class="py-0">
              <%= f.label :password , class: 'block text-gray-600 text-sm font-bold mb-2' %>
              <%= f.text_field :password, name: "employee[password]" , class: 'w-full p-2 rounded border focus:outline-none focus:ring focus:border-blue-300' %>
            </div>

            <div class="py-0">
              <%= f.label :phone_number, class: 'block text-gray-600 text-sm font-bold mb-2' %>
              <%= f.text_field :phone_number, name: "employee[phone_number]", class: 'w-full p-2 rounded border focus:outline-none focus:ring focus:border-blue-300' %>
            </div>

            <div class="py-0">
              <%= f.label :authorization_key, class: 'block text-gray-600 text-sm font-bold mb-2' %>
              <%= f.text_field :authorization_key, name: "employee[authorization_key]", class: 'w-full p-2 rounded border focus:outline-none focus:ring focus:border-blue-300' %>
            </div>

            <div class="py-4">
              <%= f.submit 'Create Employee', class: 'text-white font-bold py-2 px-4 rounded custom-bg-color' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/login.html.erb
<% @include_prose_class = true %>

<%= form_tag checkCredentials_path, method: :post do %>
    <%= text_field_tag :username %>
    <%= text_field_tag :password %>
    <%= submit_tag "Log-In", class: "bg-blue-500 text-white p-2 rounded" %>
<% end %>

app/views/employees/oldOrders.html.erb
<section class="mt-8">
    <div class="container mx-auto text-center px-4">
        <div class="flex flex-wrap -mx-4">
                <h3 class='text-xl font-bold text-gray-800 mb-2'>Old Customer Orders</h3>

                        <% @oldOrders.each do |order| %>
                            <div class="border-t-2 mt-4 pt-4 text-left border-gray-200">
                                <div class="bg-gray-100 p-3 rounded-md shadow-md mb-4">
                                    <!--<h3 class="text-xl font-semibold mb-2">Order ID: <%= order.order_id %></h3>-->
                                    <h3 class="text-xl font-semibold mb-2"><i class='fas fa-user-circle'></i> Customer: <%= Customer.find(order.customer_id).first_name %></h3>
                                    <p class="mb-1"> Phone-Number: <%= number_to_phone(Customer.find(order.customer_id).phone_number) %></p>
                                    <p class="mb-1"> Date Created: <%= order.created_at%></p>
                                    <p class="mb-1"> Date Since Created: About <%= distance_of_time_in_words(DateTime.now,order.created_at)  %> ago </p>
                                    <!--<p class="mb-1">Items:</p>-->
                                    <div class="bg-gray-200 p-2 rounded-md">

                                        <!--<p class="mb-1">Dummy item</p>-->
                                        <% amount_of_items = order.list_food_id.split(" ") %>
                                        <% result_array = amount_of_items.map do |element| %>
                                            <% int = element.gsub('"', '').to_i %>
                                            <%=Food.find_by(id: int)&.food_name %><br>
                                        <%end%>


                                    </div>
                                    <p class="font-semibold mt-2 mb-1">Total Cost: $<%= order.total_cost %></p>
                                

                                <% contents = order.list_food_notes.gsub(/\[|\]|"/, '').split(',') %>

                                <% joined_items = contents.join('') %>  <!-- Joining all items to process together -->
                                <% split_items = joined_items.split(/(\\\\)|(\\.*?\\)/) %>  <!-- Split based on backslashes and captured content -->

                                <% merged_items = [] %>
                                <% current_group = [] %>
                                <% split_items.each do |item| %>
                                    <% next if item.strip.empty? %>
                                    <% if item.start_with?('\\') && item.end_with?('\\') || item == "null" %>
                                        <% current_group.push(item) %>
                                        <% merged_items.push(current_group.join) %>
                                        <% current_group = [] %>
                                    <% else %>
                                        <% current_group.push(item) %>
                                    <% end %>
                                <% end %>


                                <% merged_items.each_with_index do |line, index| %>
                                    <div class="bg-blue-100 border border-black p-4 rounded-lg">
                                        <p><%= food_ids[index] == 0 ? Food.find(1).food_name : Food.find(food_ids[index]).food_name %></p>
                                        <% if line != "null" %>
                                            <p>Mods: <%= line %></p>
                                        <% end %>
                                    </div>
                                <% end %>



                                <p>
                                    <%= form_tag completingOrder_path, method: :post do %>
                                        <%= hidden_field_tag :id, order.id %>
                                        <%= submit_tag order.completed_order == 1 ? "Mark as Completed" : (order.completed_order == 0 ? "Mark as Started" : (order.completed_order == 2 ? "Delete Order" : "Undo")), class: "bg-gray-500 text-white p-2 rounded" %>
                                    <% end %>
                                </p>
                                </div>
                            </div>
                        <% end %>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>

<%= link_to "Back to customer orders", customer_orders_url , class: "py-4 px-3 text-gray-700 hover:text-gray-900" %>

app/views/employees/orders.html.erb
<% @include_prose_class = false %>

<style>
    .quick_options{
        margin-top: 0px !important;
        margin-bottom: 55px !important;
        margin-left: 40px !important;
        margin-right: 40px !important;
        border-color: gray;
    }
</style>

<script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>


<div class="flex flex-1 w-full flex-col items-center justify-center text-center" style="padding-top:25px !important">
    <h1 class="mx-auto max-w-4xl font-display text-3xl font-bold tracking-normal text-white-300 dark:text-gray-300 sm:text-4xl" style="color:black; margin-bottom:10px !important">
            Order
            <span class="relative whitespace-nowrap text-cyan-500 dark:text-cyan-300">
            <svg aria-hidden="true" viewBox="0 0 418 42" class="absolute top-2/3 left-0 h-[0.58em] w-full fill-cyan-500 dark:fill-cyan-300/60" preserveAspectRatio="none">
                <path d="M203.371.916c-26.013-2.078-76.686 1.963-124.73 9.946L67.3 12.749C35.421 18.062 18.2 21.766 6.004 25.934 1.244 27.561.828 27.778.874 28.61c.07 1.214.828 1.121 9.595-1.176 9.072-2.377 17.15-3.92 39.246-7.496C123.565 7.986 157.869 4.492 195.942 5.046c7.461.108 19.25 1.696 19.17 2.582-.107 1.183-7.874 4.31-25.75 10.366-21.992 7.45-35.43 12.534-36.701 13.884-2.173 2.308-.202 4.407 4.442 4.734 2.654.187 3.263.157 15.593-.780 35.401-2.686 57.944-3.488 88.365-3.143 46.327.526 75.721 2.23 130.788 7.584 19.787 1.924 20.814 1.98 24.557 1.332l.066-.011c1.201-.203 1.53-1.825.399-2.335-2.911-1.31-4.893-1.604-22.048-3.261-57.509-5.556-87.871-7.36-132.059-7.842-23.239-.254-33.617-.116-50.627.674-11.629.540-42.371 2.494-46.696 2.967-2.359.259 8.133-3.625 26.504-9.810 23.239-7.825 27.934-10.149 28.304-14.005 .417-4.348-3.529-6-16.878-7.066Z"></path>
            </svg>
            <span class="relative" style="font-family:Lilita One">Status</span>
        </span>
    </h1>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"/>

<!--
<section class="py-8">
    <div class="container mx-auto text-center px-4">
        <div class="flex flex-wrap -mx-4">
            <div class="w-full md:w-1/3 px-4 mb-8">
                <div class="bg-white p-8 shadow-md rounded-md">
                    <i class="fas fa-exclamation-triangle text-4xl text-red-500 mb-4"></i>
                    <h3 class="text-xl font-bold text-gray-800 mb-2">Not Started</h3>
                </div>
            </div>
            <div class="w-full md:w-1/3 px-4 mb-8">
                <div class="bg-white p-8 shadow-md rounded-md">
                    <i class="fas fa-circle-notch fa-spin text-4xl text-yellow-500 mb-4"></i>
                    <h3 class="text-xl font-bold text-gray-800 mb-2">Started</h3>
                </div>
            </div>
            <div class="w-full md:w-1/3 px-4 mb-8">
                <div class="bg-white p-8 shadow-md rounded-md">
                    <i class="fas fa-check text-4xl text-green-500 mb-4"></i>
                    <h3 class="text-xl font-bold text-gray-800 mb-2">Finished</h3>
                </div>
            </div>
        </div>
    </div>
</section>
-->


<section class="mt-8">
    <div class="container mx-auto text-center px-4">
        <div class="flex flex-wrap -mx-4">
            <% [0, 1, 2].each do |status| %>
            <div class="w-full md:w-1/3 px-4 mb-8">
                <div class="bg-white p-8 shadow-md rounded-md">
                <% case status
                    when 0 %>
                    <i class="fas fa-exclamation-triangle text-4xl text-red-500 mb-4"></i>
                <% when 1 %>
                    <i class="fas fa-circle-notch fa-spin text-4xl text-yellow-500 mb-4"></i>
                <% when 2 %>
                    <i class="fas fa-check text-4xl text-green-500 mb-4"></i>
                <% else %>
                    <i class="fas fa-question text-gray-500 mb-4"></i>
                <% end %>
                <%= case status
                    when 0
                        "<h3 class='text-xl font-bold text-gray-800 mb-2'>Not Started</h3>"
                    when 1
                        "<h3 class='text-xl font-bold text-gray-800 mb-2'>Started</h3>"
                    when 2
                        "<h3 class='text-xl font-bold text-gray-800 mb-2'>Completed</h3>"
                    else
                        "<h3 class='text-xl font-bold text-gray-800 mb-2'>Unknown</h3>"
                end.html_safe %>

                        <% @orders.select { |order| order.completed_order == status }.each do |order| %>
                            <div class="border-t-2 mt-4 pt-4 text-left border-gray-200">
                                <div class="bg-gray-100 p-3 rounded-md shadow-md mb-4">
                                    <!--<h3 class="text-xl font-semibold mb-2">Order ID: <%= order.order_id %></h3>-->
                                    <h3 class="text-xl font-semibold mb-2"><i class='fas fa-user-circle'></i> Customer: <%= Customer.find(order.customer_id).first_name %></h3>
                                    <p class="mb-1"> Phone-Number: <%= number_to_phone(Customer.find(order.customer_id).phone_number) %></p>
                                    <!--<p class="mb-1">Items:</p>-->
                                    <div class="bg-gray-200 p-2 rounded-md">

                                        <!--<p class="mb-1">Dummy item</p>-->
                                        <% amount_of_items = order.list_food_id.split(" ") %>
                                        <% result_array = amount_of_items.map do |element| %>
                                            <% int = element.gsub('"', '').to_i %>
                                            <%=Food.find_by(id: int)&.food_name %><br>
                                        <%end%>


                                    </div>
                                    <p class="font-semibold mt-2 mb-1">Total Cost: $<%= order.total_cost %></p>
                                

                                <% contents = order.list_food_notes.gsub(/\[|\]|"/, '').split(',') %>

                                <% joined_items = contents.join('') %>  <!-- Joining all items to process together -->
                                <% split_items = joined_items.split(/(\\\\)|(\\.*?\\)/) %>  <!-- Split based on backslashes and captured content -->

                                <% merged_items = [] %>
                                <% current_group = [] %>
                                <% split_items.each do |item| %>
                                    <% next if item.strip.empty? %>
                                    <% if item.start_with?('\\') && item.end_with?('\\') || item == "null" %>
                                        <% current_group.push(item) %>
                                        <% merged_items.push(current_group.join) %>
                                        <% current_group = [] %>
                                    <% else %>
                                        <% current_group.push(item) %>
                                    <% end %>
                                <% end %>


                                <% merged_items.each_with_index do |line, index| %>
                                    <div class="bg-blue-100 border border-black p-4 rounded-lg">
                                        <p><%= food_ids[index] == 0 ? Food.find(1).food_name : Food.find(food_ids[index]).food_name %></p>
                                        <% if line != "null" %>
                                            <p>Mods: <%= line %></p>
                                        <% end %>
                                    </div>
                                <% end %>



                                <p>
                                    <%= form_tag completingOrder_path, method: :post do %>
                                        <%= hidden_field_tag :id, order.id %>
                                        <%= submit_tag order.completed_order == 1 ? "Mark as Completed" : (order.completed_order == 0 ? "Mark as Started" : "Remove"), class: "bg-gray-500 text-white p-2 rounded" %>
                                    <% end %>
                                </p>
                                </div>
                            </div>
                        <% end %>
                </div>
            </div>
            <% end %>
            </div>
        </div>
    </div>
</section>


<div class="container mx-auto mt-2 border-t-2 mb-6" style="padding-top:10px !important">
  <%= form_tag adminKey_path, method: :post do %>
    <div class="max-w-sm mx-auto mt-6 bg-white rounded-md shadow-md overflow-hidden">
      <div class="px-6 py-4 bg-cyan-500 text-white">
        <h1 class="text-lg font-bold" style="color:white">Admin Login</h1>
      </div>
      <div class="px-6 py-4">
        <div class="mb-4">
          <label class="block text-gray-700 font-bold mb-2">Admin Password</label>
          <%= text_field_tag :authorizationKey %>
        </div>

        <div class="mt-2">
          <%= button_tag(type: 'submit', class: 'bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded') do %>
            <%= content_tag(:i, '', class: '', style: '') %> Login
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "Older Orders", employees_old_orders_url , class: "py-4 px-3 text-gray-700 hover:text-gray-900" %>

app/views/employees/show.html.erb
<% @include_prose_class = true %>


<%= link_to "Go Back", employees_home_path, class: "btn btn-primary" %>
<div class="rounded-lg bg-indigo-200 p-4 food-additions-container">
  <h1>Food Name: <%= @food.food_name %></h1>
  <% data = JSON.parse(@food.food_additions) rescue [] %>
  <% additions = data.is_a?(Array) ? data : [data] %>
  <h3>Possible Food Additions</h3>
  <% additions.each do |addition| %>
    <h6><%= addition['addition_name'] %> &nbsp$<%= addition['cost'] %></h6>
  <% end %>
  <h4>Initial Cost $<%= @food.inital_cost %></h4>
</div>


<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 mt-4">
  <% if @additions.any? %>
    <% @additions.each do |addition| %>
      <div class="bg-white shadow-md rounded-lg p-4 overflow-hidden">
        <h2 class="text-lg font-bold mb-2">Food Addition: <%= addition.addition_name %></h2>
        <p class="text-sm">Cost: <%= addition.cost %></p>
        <div class="mt-4">
          <%= form_tag storing_additions_path, method: :post do %>
            <%= hidden_field_tag "selected_addition[#{addition.addition_name}_cost]", addition.cost %>
            <%= check_box_tag "selected_addition[#{addition.addition_name}]", addition.id, nil, data: { cost: addition.cost, id: addition.id, isRadioButton: addition.isRadioButton } %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="col-span-3">No additions available.</p>
  <% end %>
</div>


<textarea readonly rows="5" class="w-full bg-white border p-2 mt-4" id="selected-additions-output"></textarea>

<h1>TESTING #NOTE DO ADDITIONS BEFORE DOING</h1>
<%= form_tag updatingFoodAdditions_path, method: :post do %>
  <%= hidden_field_tag :id, @food.id %>
  <%= text_field_tag 'foodAdditions', nil, id: "food_modifications_textbox" %>
  <%= submit_tag "Update Food", class: "bg-green-500 text-white p-2 rounded" %>
<% end %>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    var outputTextarea = document.getElementById("selected-additions-output");
    var label = document.getElementById("food_modifications_textbox");
    console.log(label.value);

    checkboxes.forEach(checkbox => {
      checkbox.addEventListener("change", function() {
        var selectedAdditions = Array.from(checkboxes)
          .filter(cb => cb.checked)
          .map(cb => {
            var id = parseInt(cb.dataset.id);
            var name = cb.getAttribute('name').replace('selected_addition[', '').replace(']', '');
            var cost = parseFloat(cb.dataset.cost);
            var radioButton = cb.dataset.isradiobutton;
            var created_at = cb.dataset.created_at;
            var updated_at = cb.dataset.updated_at; 
            return `{"id"=>${id}, "addition_name"=>"${name}", "cost"=>${cost}, "isRadioButton"=>${radioButton}, "created_at"=>"${created_at}", "updated_at"=>"${updated_at}"}`;
          });

        outputTextarea.value = JSON.stringify(selectedAdditions);
        label.value = `[${selectedAdditions.join(', ')}]`;
        console.log(label.value);
      });
    });
    console.log(label.value);
  });
</script>