config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #All of our Resources
  resources :customers
  resources :employees
  resources :additions
  resources :foods
  resources :temp_orders
  resources :orders
  resources :food_tags

  #The Home Page of the website
  root 'pages#home'
  #addition !!
  #This will be our testing file for things you would like to testout using the website: (Please Comment this route out when development is over)
  get 'test', to: 'menu#testing', as: 'test'

  #Employee Routes 
  get 'n1e2w3E4m5p6l7o8y9e0R1e2g3i4s5t6e7r8', to: 'employees#admin', as: 'employees_login' #Adding New Employees
  get '1a2d3m4i5n6H7u8b', to: 'employees#home', as: 'employees_home' #Administration Hub :: if the Authorization Key inst correct will redirect you to login or to Non Admin Orders View
  get '1c2u3s4t5o6m7e8r9O0r1d2e3r4s', to: 'employees#orders', as: 'customer_orders' #Customer's Order View :: Shows all non started orders
  get '1E2m3p4l5o6y7e8L9o0g1i2n', to: 'employees#login', as: 'employees_admin_login' #Employee Login
  get 'o1l2d3O4r5d6e7r8s9', to: 'employees#oldOrders', as: 'employees_old_orders' #Employee Login

  #Routes for customers to order Items
  get 'confirmation', to: 'menu#confirmation', as: 'order_confirmation'
  get 'orderingMenu', to: 'menu#orderingMenu', as: 'ordering_menu'
  get 'order', to: 'menu#order', as: 'menu_order'
  get 'login', to: 'menu#login'
  get 'icecreamMenu', to: 'menu#iceCreamMenu', as: 'ice_memu'

  #Setting what menu will be shown for the ordering menu 
  get '/set_isBreakfast_true', to: 'menu#set_isBreakfast_true'
  get '/set_isBreakfast_false', to: 'menu#set_isBreakfast_false'

  #Methods in the Employees Controller
  post 'storing_additions', to: 'employees#addition'
  post 'deletingAdditions', to: 'employees#deletingAdditions'
  post 'deletingFoods', to: 'employees#deletingFoods'
  post 'addingNewFood', to: 'employees#addingFood'
  post 'completingOrder', to: 'employees#completingOrder'
  post 'changingTag', to: 'employees#changingTag'
  post 'deletingTags', to: 'employees#deletingTags'
  post 'updatingFoodAdditions', to: 'employees#updatingFoodAdditions'
  post 'checkCredentials', to: 'employees#checkCredentials'
  post 'adminKey', to: 'employees#adminKey'

  #Theses Methods are for forums inside of the menu controller
  post 'deleteTempOrderItem', to: 'menu#deleteTempOrderItem'
  post 'updatingCustomersOrder', to: 'menu#updatingCustomersOrder'

  Rails.application.routes.draw do
    get 'menu/show/:id', to: 'menu#show', as: 'menu_show' # Define a route for showing food details
  end

  Rails.application.routes.draw do
    get 'employees/show/:id', to: 'employees#show', as: 'employees_show' # Define a route for showing food details
  end

end

app/models/addition.rb
class Addition < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/food_tag.rb
class FoodTag < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/temp_order.rb
class TempOrder < ApplicationRecord
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController

    def testing
        @temp_order = TempOrder.new
        @temp_orders = TempOrder.all

        @food = Food.find_by(id: 5)
        @testingFoods = Food.where("id < ?", 3)
        Time.zone = 'Eastern Time (US & Canada)'
        session["Time"] = Time.zone.now
        
        @total = 0
        if @customers_temp_orders
          @customers_temp_orders.each do |foodItem|
            @total += (foodItem.total_cost).to_f
          end
        end

        @viewableMenu = params[:value]
        @lunchAndDinnerMenu = Food.where(isBreakfast: false)
        @breakfastMenu = Food.where(isBreakfast: true)
    end

    def login
        session[:employee] = nil
        session[:authorization_key] = nil
        session[:customer] = nil
    end

    def show #shows the menu item clicked on
        session[:employee] = nil
        session[:authorization_key] = nil
        session[:customer]
        @food = Food.find(params[:id])
    end

    def iceCreamMenu #ice cream menu
        session[:employee] = nil
        session[:authorization_key] = nil
        session[:customer] = Customer.find_by(first_name: session[:firstName],phone_number: session[:phoneNumber]) || nil
        if !session[:customer].nil?
            @customers_temp_orders = TempOrder.where(customer_id: session[:customer]["id"])
        end

        Time.zone = 'Eastern Time (US & Canada)'
        session["Time"] = Time.zone.now
        
        @total = 0
        if @customers_temp_orders
          @customers_temp_orders.each do |foodItem|
            @total += (foodItem.total_cost).to_f
          end
        end
    end

    def orderingMenu #Grabs value from previous page and Adds logged in customer information to the session
        session[:employee] = nil
        session[:authorization_key] = nil
        session[:customer] = Customer.find_by(first_name: session[:firstName],phone_number: session[:phoneNumber]) || nil
        if !session[:customer].nil?
            @customers_temp_orders = TempOrder.where(customer_id: session[:customer]["id"])
        end

        Time.zone = 'Eastern Time (US & Canada)'
        session["Time"] = Time.zone.now
        
        @total = 0
        if @customers_temp_orders
          @customers_temp_orders.each do |foodItem|
            @total += (foodItem.total_cost).to_f
          end
        end

        @viewableMenu = params[:value]
        @lunchAndDinnerMenu = Food.where(isBreakfast: false)
        @breakfastMenu = Food.where(isBreakfast: true)
    end

    def confirmation
        session[:employee] = nil
        session[:authorization_key] = nil
        if session[:customer].nil? || session[:customer].blank?
            redirect_to :root
        end
        @orders = Order.where(customer_id: session["customer"]["id"])
    end

    def order
        session[:employee] = nil
        session[:authorization_key] = nil
        Time.zone = 'Eastern Time (US & Canada)'
        session["Time"] = Time.zone.now
        @temp_order = TempOrder.new
        @temp_orders = TempOrder.all

        @foods = Food.all
        session[:customer] = Customer.find_by(first_name: session[:firstName],phone_number: session[:phoneNumber])
        if session[:customer] != nil
            @customers_temp_orders = TempOrder.where(customer_id: session[:customer].id)
            @total = 0
            if @customers_temp_orders
                @customers_temp_orders.each do |foodItem|
                    @total += (foodItem.total_cost).to_f
                end
            end
        end
    end

    def set_isBreakfast_true
        session[:isBreakfast] = true
        redirect_to ordering_menu_path
    end

    def set_isBreakfast_false
        session[:isBreakfast] = false
        redirect_to ordering_menu_path
    end

    def deleteTempOrderItem
        @customersTempFood = TempOrder.find_by(customer_id: session[:customer]["id"], food_id: params[:foodId])
        if !@customersTempFood.nil?
            @customersTempFood.destroy
            updatingCustomersOrder()
            redirect_to ordering_menu_path
        else
            puts "Error ------------------"
            redirect_to ordering_menu_path
        end
    end

    def updatingCustomersOrder
        puts TempOrder.where(customer_id: session[:customer]["id"])
    end
end

app/helpers/additions_helper.rb
module AdditionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/food_tags_helper.rb
module FoodTagsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/temp_orders_helper.rb
module TempOrdersHelper
end

app/helpers/testing_helper.rb
module TestingHelper
end

app/views/layouts/application.html.erb
<% content_for :prose_class do %>
  <%= "prose" %>
<% end %>
<!DOCTYPE html>
<html>
  <head>
    <title>ProductionDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lilita+One&display=swap">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  </head>
  
  <%# navbar %> 
  <% if session[:employee].nil? %>
  <nav class="bg-gray-100" style="">
    <div class="max-w-5xl mx-auto px-4">
      <div class="flex justify-between">

  
      <%# logo %>
      <div class="flex space-x-4">
        <div>
        <a href="https://lsscse.com" class="flex items-center py-5 px-2 text-gray-800">
          <svg class="h-6 w-6 mr-1" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512" fill="#0CC0DF"> 
            <path d="M368 160h-.94a144 144 0 1 0-286.12 0H80a48 48 0 0 0 0 96h288a48 48 0 0 0 0-96zM195.38 493.69a31.52 31.52 0 0 0 57.24 0L352 288H96z"/>
          </svg>
          <span class="font-bold">Lickity Splitz </span>
          
        </a>
        </div>
    
        <%# primary nav %>
        <div class="flex items-center space-x-1 hidden md:flex">
        <%= link_to "Menu", menu_order_path, class: "py-4 px-3 text-gray-700 hover:text-gray-900" %>

          <%= link_to "Ice Cream Flavors", ice_memu_url , class: "py-4 px-3 text-gray-700 hover:text-gray-900" %>

        </div>
      </div>
  
      <%# secondary nav %>
      <div class="flex items-center space-x-1 hidden md:flex">
          <a href="https://www.google.com/maps/dir//231+Main+St,+Winchendon,+MA+01475/@42.6698047,-72.1603031,12z/data=!4m9!4m8!1m0!1m5!1m1!1s0x89e15d89409df463:0x913e4cc313dee698!2m2!1d-72.0779019!2d42.669708!3e0?entry=ttu" class="py-4 px-3 text-gray-700 hover:text-gray-900">Get Directions</a>
            <% if session[:customer].nil? %>
              <%= link_to "Place an Order", login_path, class: "py-2 px-3 text-gray-700 hover:text-gray-900 text-white rounded", style: "background-color: #0CC0DF" %>
            <% else %>
              <button id="open_customer_view" type="button" class="relative inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" style="background-color:#0CC0DF">
                <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512" style="padding-right:5px;">
                <path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z" fill="white"/>
                </svg>
                <span class="sr-only"></span>Your Order
                <% temp_order_count = TempOrder.where(customer_id: session[:customer]["id"]).length %>
                <% if temp_order_count != 0 %>
                <div class="absolute inline-flex items-center justify-center w-6 h-6 text-xs font-bold text-white bg-red-500 border-2 border-white rounded-full -top-2 -end-2 dark:border-gray-900"><%= TempOrder.where(customer_id: session[:customer]["id"]).length %></div>
                <% end %>
            </button>
            <% end %>
      </div>

      <script>
          document.getElementById('open_customer_view').addEventListener('click', function () {
            document.getElementById('customer_view_overlay').style.display = 'flex';
        });

        document.getElementById('close_customer_view').addEventListener('click', function () {
            document.getElementById('customer_view_overlay').style.display = 'none';
        });
        document.getElementById('close_customer').addEventListener('click', function () {
            document.getElementById('customer_view_overlay').style.display = 'none';
        });
      </script>

      <%# mobile button goes here %>
      <div class="flex items-center md:hidden">
        <button id="toggleButton" class="mobile-menu-button">
          <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#0CC0DF" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5" />
          </svg>
        </button>
      </div>

      </div>
  
    </div>


  
  <%# mobile view %>
  <div class="mobile-menu hidden">
    <% if session[:customer].nil? %>
      <a class="block py-2 px-4 text-sm hover:bg-gray-200" href=<%= root_url%>>Home</a>
      <a class="block py-2 px-4 text-sm hover:bg-gray-200" href="<%= login_path%>">Login</a>
      <a class="block py-2 px-4 text-sm hover:bg-gray-200" href="<%= menu_order_path%>">View Menu's</a>
    <% else %>
      <button id="open_customer_view" type="button" class="relative inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" style="background-color:#0CC0DF">
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512" style="padding-right:5px;">
        <path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z" fill="white"/>
        </svg>
        <span class="sr-only"></span>Your Order
        <% temp_order_count = TempOrder.where(customer_id: session[:customer]["id"]).length %>
        <% if temp_order_count != 0 %>
        <div class="absolute inline-flex items-center justify-center w-6 h-6 text-xs font-bold text-white bg-red-500 border-2 border-white rounded-full -top-2 -end-2 dark:border-gray-900"><%= TempOrder.where(customer_id: session[:customer]["id"]).length %></div>
        <% end %>
    </button>
    <% end %>
  </div>

    <script>
    const btn = document.querySelector('button.mobile-menu-button');
    const menu = document.querySelector('.mobile-menu');
    btn.addEventListener('click', () => {
      menu.classList.toggle('hidden');
    })

    $(document).ready(function() {
    let isMenuOpen = false;
    
    // Reference to the button and its SVG
    const button = $("#toggleButton");
    const svg = button.find("svg");
    
    // Define the SVG for the open and closed states
    const svgClosed = '<path stroke-linecap="round" stroke-linejoin="round" d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5" />';
    const svgOpen = '  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />';

    // Function to toggle the button's state and change the SVG
    function toggleButton() {
      isMenuOpen = !isMenuOpen;
      if (isMenuOpen) {
        svg.html(svgOpen);
      } else {
        svg.html(svgClosed);
      }
    }
    
    // Add a click event listener to the button
    button.on("click", toggleButton);
  });
  </script>
  
  </nav>
  <%end%>

  
  <%# content %>
  
  <body class="">

    <div class="<%= @include_prose_class ? 'prose' : '' %> mx-auto">
      <%= yield %>
    </div>

  </body>

<% if session[:employee].nil? %>
<div style = "padding-top:5px"> <!-- White space above footy -->
  <div style="padding-top:20px !important">
    <div class="bg-gray-100 mt-3" style="padding-top:10px !important; padding-bottom:10px !important">
      <div class="max-w-screen-lg py-3 px-4 sm:px-6 text-gray-800 sm:flex justify-between mx-auto">
          <div class="p-2 sm:w-2/12 border-r">
              <div class="text-sm uppercase font-bold" style="color:#0CC0DF">Quick Links</div>
              <ul>
                  <li class="my-2">
                      <a class="hover:text-cyan-500" href=<%= root_url%>>Home</a>
                  </li>
                  <li class="my-2">
                      <a class="hover:text-cyan-500" href="<%= login_path%>">Login</a>
                  </li>
                  <li class="my-2">
                      <a class="hover:text-cyan-500" href="<%= login_path%>">Place an Order</a>
                  </li>
                  <li class="my-2">
                      <a class="hover:text-cyan-500" href="<%= menu_order_path%>">View Menu's</a>
                  </li>
              </ul>
          </div>
          <div class="p-2 sm:w-7/12 border-r text-center">
          
              <h3 class="font-bold text-xl mb-4 text-gray-700">Lickity Splitz</h3>

              <p class="text-gray-500 text-sm mb-10">Under new ownership, the restaurant radiates warmth with its enthusiastic staff, lively ambiance, and mouthwatering dishes, creating an inviting and engaging dining experience.</p>
          </div>
          <div class="p-2 sm:w-3/12">
              <div class="text-sm uppercase font-bold" style="color:#0CC0DF">Contact Us</div>
              <ul>
                  <li class="my-2">
                      <a href="https://www.google.com/maps/dir//Lickity+Splitz,+231+Main+St,+Winchendon,+MA+01475/@42.536082,-72.385826,9z/data=!4m9!4m8!1m0!1m5!1m1!1s0x89e15d897d57009b:0x886184d8c00a3064!2m2!1d-72.0778735!2d42.6697029!3e0?entry=ttu" class="hover:text-cyan-500" target = "_blank"><i class="fa fa-map-marker" style="color:black"></i> 231 Main St, <br>Winchendon, MA</a>
                  </li>
                  <li class="my-2">
                    <a style="text-decoration:none !important" href="tel:(978) 297-1777" class="hover:text-cyan-500"><i class="fa fa-phone" style="color:black"></i> (978) 297-1777</a>              
                  </li>
                  <li class="my-2">
                    <p><i class="fa fa-bell" style="color:black"></i> Takeout · Dine-in · Outdoor seating</p>
                  </li>
              </ul>
          </div>
      </div>
      <div class="flex py-1 m-auto text-gray-800 text-sm flex-col items-center border-t max-w-screen-xl">
          <div class="md:flex-auto md:flex-row-reverse mt-2 flex-row flex">
              <a href="https://www.facebook.com/lickitysplitzwinchendon/" class="w-6 mx-1">
                <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 320 512">
                  <path d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"/>
                </svg>
              </a>

              <a href="https://www.yelp.com/biz/lickity-splitz-winchendon" class="w-6 mx-1">
                                <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 384 512">
                        <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                        <path d="M42.9 240.32l99.62 48.61c19.2 9.4 16.2 37.51-4.5 42.71L30.5 358.45a22.79 22.79 0 0 1-28.21-19.6 197.16 197.16 0 0 1 9-85.32 22.8 22.8 0 0 1 31.61-13.21zm44 239.25a199.45 199.45 0 0 0 79.42 32.11A22.78 22.78 0 0 0 192.94 490l3.9-110.82c.7-21.3-25.5-31.91-39.81-16.1l-74.21 82.4a22.82 22.82 0 0 0 4.09 34.09zm145.34-109.92l58.81 94a22.93 22.93 0 0 0 34 5.5 198.36 198.36 0 0 0 52.71-67.61A23 23 0 0 0 364.17 370l-105.42-34.26c-20.31-6.5-37.81 15.8-26.51 33.91zm148.33-132.23a197.44 197.44 0 0 0-50.41-69.31 22.85 22.85 0 0 0-34 4.4l-62 91.92c-11.9 17.7 4.7 40.61 25.2 34.71L366 268.63a23 23 0 0 0 14.61-31.21zM62.11 30.18a22.86 22.86 0 0 0-9.9 32l104.12 180.44c11.7 20.2 42.61 11.9 42.61-11.4V22.88a22.67 22.67 0 0 0-24.5-22.8 320.37 320.37 0 0 0-112.33 30.1z"/>
                    </svg>
              </a>


          </div>
          <div class="my-5">© Copyright 2023. All Rights Reserved.</div>
      </div>
      </div>
      </div>
  </div>
  <%end%>

</html>
  